"""
Constants shared across the module
"""
USB_ID_VENDOR = 0x04D8
USB_ID_PRODUCT = 0xF372

MODE_COLOUR = 1
MODE_FADE = 2
MODE_STROBE = 3
MODE_WAVE = 4
MODE_DEMO = 6

MODES = (MODE_COLOUR, MODE_FADE, MODE_STROBE, MODE_WAVE, MODE_DEMO)

LED_FLAG_BOTTOM = 1
LED_FLAG_MIDDLE = 2
LED_FLAG_TOP = 3
LED_POLE_BOTTOM = 4
LED_POLE_MIDDLE = 5
LED_POLE_TOP = 6

LED_FLAG_ALL = 65
LED_POLE_ALL = 66
LED_ALL = 255

LEDS = (
    LED_ALL, LED_FLAG_ALL, LED_POLE_ALL, 
    LED_FLAG_BOTTOM, LED_FLAG_MIDDLE, LED_FLAG_TOP,
    LED_POLE_BOTTOM, LED_POLE_MIDDLE, LED_POLE_TOP,
)
